spring:
  application:
    name: ping-ai-agent
  profiles:
    active: local
#  ai:
#    ollama:
#      base-url: http://localhost:11434
#      chat:
#        model: qwen2.5:0.5b
server:
  port: 8123
  servlet:
    context-path: /api

# springdoc-openapi 接口文档配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.ping.aiagent.controller
# knife4j 的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
logging:
  level:
    org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor: debug