spring:
  application:
    name: ping-ai-agent
  profiles:
    active: local
  # 启用工具调用内容和结果的记录
  ai:
    tools:
      observations:
        include-content: true

  # 启用 mcp
    mcp:
      client:
#        sse:
#          connections:
#            sever1:
#              url: http://localhost:8127
        stdio:
          servers-configuration: classpath:mcp-servers.json


#  ai:
#    ollama:
#      base-url: http://localhost:11434
#      chat:
#        model: qwen2.5:0.5b
server:
  port: 8123
  servlet:
    context-path: /api

# springdoc-openapi config
#springdoc:
#  swagger-ui:
#    path: /swagger-ui.html
#    tags-sorter: alpha
#    operations-sorter: alpha
#  api-docs:
#    path: /v3/api-docs
#  group-configs:
#    - group: 'default'
#      paths-to-match: '/**'
#      packages-to-scan: com.ping.aiagent.controller

# knife4j 的增强配置，不需要增强可以不配
#knife4j:
#  enable: true
#  openapi:
#    title: ping-ai-agent
#    description: ping-ai-agent
#    version: 1.0.0
#  setting:
#    language: zh_cn


logging:
  level:
    org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor: debug
    org.springframework.ai: DEBUG
